### PR TITLE
Added headings field

### PR DESCRIPTION
**Pull request by avigoldman**
Working towards #1 

merge after #30

### CODE REVIEW

**Comment by ChristopherBiscardi** [comment]
you're on a roll today 😄

**Comment by avigoldman** [comment]
Vacation 😜

**Comment by chasemccoy** [comment]
This doesn't seem to be working for me on the latest version. Has this been published yet?

**Comment by ChristopherBiscardi** [comment]
@chasemccoy Released in 0.0.8. Thanks for the ping.

**Pull request merged**
