### PR TITLE
exposing plugins that implement wrapRootElement

### PR DESCRIPTION
**Pull request by ChristopherBiscardi**

### CODE REVIEW

**Comment by mmmaaatttttt** [comment]
Hey @ChristopherBiscardi - just taking another look at this now. I'm having trouble dynamically loading the relevant root wrappers inside of `wrap-root-render-html-entry`. With a static file path, everything's great, but otherwise I'm running into issues. 

For example, consider the following:

```js
const myPath = "/Users/me/project";
const empty = "";

// works great
const test1 = (await import("/Users/me/project/gatsby-ssr.js")).wrapRootElement;

// works great
const test2 = (await import("/Users/me/project" + "/gatsby-ssr.js")).wrapRootElement;

// both break with 2 errors, one unexpected token,
// one require function is used in a way in which dependencies cannot be statically extracted
const test3 = (await import(myPath + "/gatsby-ssr.js")).wrapRootElement;
const test4 = (await import("/Users/me/project" + empty + "/gatsby-ssr.js")).wrapRootElement;

// breaks with module nod found error
const test5 = (await import(`${myPath}/gatsby-ssr.js`)).wrapRootElement;
```

Any suggestions on how to proceed? I'm not quite sure why these imports are failing, and am hoping there's something simple I'm missing.

**Comment by ChristopherBiscardi** [comment]
There's an import that handles the scopes here in the entry file: https://github.com/ChristopherBiscardi/gatsby-mdx/blob/423e54d149682738b37f7ec371d31d660ef2444d/packages/gatsby-mdx/utils/wrap-root-render-html-entry.js#L4

In a similar way, we use [another loader to pull in the plugins](https://github.com/ChristopherBiscardi/gatsby-mdx/blob/423e54d149682738b37f7ec371d31d660ef2444d/packages/gatsby-mdx/wrap-root-element.js#L28) in other areas of the project. You should likely do something similar [to the mdx-components loader](https://github.com/ChristopherBiscardi/gatsby-mdx/blob/423e54d149682738b37f7ec371d31d660ef2444d/packages/gatsby-mdx/loaders/mdx-components.js), which uses a loader to `require` plugins through webpack. There's a special config that makes the loader handle it's own file: https://github.com/ChristopherBiscardi/gatsby-mdx/blob/423e54d149682738b37f7ec371d31d660ef2444d/packages/gatsby-mdx/gatsby/create-webpack-config.js#L34

**Comment by mmmaaatttttt** [comment]
@ChristopherBiscardi Thanks for the support! This PR now fixes the issue with my project. Let me know what you think. Right now I'm only tackling support for `wrapRootElement` - let me know whether you think the fix should be more ambitious.

Also while I'm in here, happy to tackle #250 as well - let me know whether you'd rather have that be part of a separate PR.

**Comment by ChristopherBiscardi** [comment]
Looks great, thanks!

**Comment by ChristopherBiscardi** [comment]
@mmmaaatttttt #250 would be dope too, but definitely do it in a different PR

**Pull request merged**
